name: load testing

on:
  push:
    branches: [ master ]

env:
  HOST: http://0.0.0.0:8080


jobs:

  cache-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install dependencies
        run: pip3 install -r requirements.txt
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip

  loadtest:
    runs-on: ubuntu-latest
    needs: [cache-requirements]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install dependencies
        run: pip3 install -r requirements.txt
      - name: load test
        run: |
              json_output=$(locust -f test/test_load/single_api_single_payload.py \
                  --headless \
                  --host $HOST \
                  --spawn-rate 1 \
                  --users 5 \
                  --run-time 60 \
                  --html report.html \
                  --json)
