name: load testing

on:
  push:
    branches: [ master ]

env:
  HOST: http://0.0.0.0:8080


jobs:

  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install dependencies
        run: pip3 install -r requirements.txt
      - name: run fastapi locally
        run: |
              cd project
              nohup python3 app.py > /dev/null 2>&1 &
              sleep 2
      - name: load test
        run: |
              json_output=$(locust -f test/test_load/single_api_single_payload.py \
                  --headless \
                  --host $HOST \
                  --spawn-rate 1 \
                  --users 5 \
                  --run-time 20 \
                  --exit-code-on-error 0 \
                  --csv report.csv \
                  --html report.html)
      - name: load test summary
        run: |   
              req_total=$(awk -F',' 'END {print $3}' report.csv_stats.csv)
              req_fail=$(awk -F',' 'END {print $4}' report.csv_stats.csv)
              fail_rate=$(( (req_fail + req_total) / 100 ))
              rps=$(awk -F',' 'END {print $10}' report.csv_stats.csv)
              p90=$(awk -F',' 'END {print $16}' report.csv_stats.csv)
              p95=$(awk -F',' 'END {print $17}' report.csv_stats.csv)
              p99=$(awk -F',' 'END {print $19}' report.csv_stats.csv)

              echo Fail Rate: ${fail_rate}%
              echo RPS: $rps
              echo 90 Percentile: ${p90}ms
              echo 95 Percentile: ${p95}ms
              echo 99 Percentile: ${p99}ms
      - name: store locust report
        uses: actions/upload-artifact@v3
        with:
          name: locust-report
          path: report.html
